name: Toffee Auto Playlist

on:
  schedule:
    - cron: "0 */6 * * *"   # প্রতি ৬ ঘণ্টায় (UTC)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOFFEE_JWT: ${{ secrets.TOFFEE_JWT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install requests

      - name: Run script
        run: python toffee_play.py

      - name: Commit and push generated m3u
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add toffee_channels.m3u || true
          git commit -m "🔄 Auto update toffee playlist" || echo "No changes"
          git push || echo "Push failed"
